version: "3"

services:
  # PROXY running in nginx
  nginx:
    image: nginx
    networks:
      - peptest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  # PEP: running app `peptest -auth`
  pep:
    build: ./app
    image: $USER/peptest
    command: ["-auth"]
    networks:
      - peptest
  # ADES: running app `peptest -resource`
  ades:
    image: $USER/peptest
    depends_on:
      - pep
    command: ["-resource"]
    networks:
      - peptest

networks:
  peptest:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.234.0/24
